version: '3'

volumes:
    prometheus_data: {}
    grafana_data: {}

services:
  graph-node:

    build:
      context: .  # Replace with the path to your Dockerfile directory
      dockerfile: Dockerfile.custom  # Replace with the name of your Dockerfile if it's not named 'Dockerfile'
    container_name: graph-node-momodu
    ports:
      - '127.0.0.1:8000:8000'
      - '127.0.0.1:8001:8001'
      - '127.0.0.1:8020:8020'
      - '127.0.0.1:8030:8030'
      - '127.0.0.1:8040:8040'
    depends_on:
      - ipfs
      - postgres
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      postgres_host: postgres
      postgres_user: graph-node
      postgres_pass: let-me-in
      postgres_db: graph-node
      ipfs: 'https://ipfs-api.x.superfluid.dev'
      ethereum: 'polygon-zkevm-testnet:https://polygon-zkevm-testnet.sfrpc.x.superfluid.dev?app=graph'
      GRAPH_LOG: info
    volumes:
      - ./health_check/health_check.sh:/health_check.sh
    healthcheck:
      test: ["CMD", "bash", "/health_check.sh", "http://localhost:8030/graphql", "protocol-v1-polygon-zkevm-testnet"] # Command to check health.
      interval: 5s # Interval between health checks.
      timeout: 5s # Timeout for each health checking.
      retries: 20 # Hou many times retries.
      start_period: 10s # Estimated time to boot.

  ipfs:
    image: ipfs/go-ipfs:v0.10.0
    ports:
      - '5001:5001'
    volumes:
      - ./data/ipfs:/data/ipfs
  postgres:
    image: postgres:14
    ports:
      - '5432:5432'
    command:
      [
        "postgres",
        "-cshared_preload_libraries=pg_stat_statements"
      ]
    environment:
      POSTGRES_USER: graph-node
      POSTGRES_PASSWORD: let-me-in
      POSTGRES_DB: graph-node
      # FIXME: remove this env. var. which we shouldn't need. Introduced by
      # <https://github.com/graphprotocol/graph-node/pull/3511>, maybe as a
      # workaround for https://github.com/docker/for-mac/issues/6270?
      PGDATA: "/var/lib/postgresql/data"
      POSTGRES_INITDB_ARGS: "-E UTF8 --locale=C"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
